package model.pojo;
// Generated 5/11/2015 05:15:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int idCategoria;
     private String nombre;
     private String descripcion;
     private String foto;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public Categoria(int idCategoria, String nombre, String descripcion,String foto, Set productos) {
       this.idCategoria = idCategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productos = productos;
       this.foto=foto;
    }
   
    public int getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(int idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


