package model.pojo;
// Generated 5/11/2015 05:15:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apePat;
     private String apeMat;
     private String correo;
     private String sexo;
     private String contrasena;
     private Set pedidos = new HashSet(0);
     private Set listadeseos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Cliente(int idCliente, String nombre, String apePat, String apeMat, String correo, String sexo, String contrasena, Set pedidos, Set listadeseos) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apePat = apePat;
       this.apeMat = apeMat;
       this.correo = correo;
       this.sexo = sexo;
       this.contrasena = contrasena;
       this.pedidos = pedidos;
       this.listadeseos = listadeseos;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApePat() {
        return this.apePat;
    }
    
    public void setApePat(String apePat) {
        this.apePat = apePat;
    }
    public String getApeMat() {
        return this.apeMat;
    }
    
    public void setApeMat(String apeMat) {
        this.apeMat = apeMat;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getListadeseos() {
        return this.listadeseos;
    }
    
    public void setListadeseos(Set listadeseos) {
        this.listadeseos = listadeseos;
    }




}


