package model.pojo;
// Generated 5/11/2015 05:15:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estadopedido generated by hbm2java
 */
public class Estadopedido  implements java.io.Serializable {


     private int idEstadoPedido;
     private String nombre;
     private Set pedidos = new HashSet(0);

    public Estadopedido() {
    }

	
    public Estadopedido(int idEstadoPedido) {
        this.idEstadoPedido = idEstadoPedido;
    }
    public Estadopedido(int idEstadoPedido, String nombre, Set pedidos) {
       this.idEstadoPedido = idEstadoPedido;
       this.nombre = nombre;
       this.pedidos = pedidos;
    }
   
    public int getIdEstadoPedido() {
        return this.idEstadoPedido;
    }
    
    public void setIdEstadoPedido(int idEstadoPedido) {
        this.idEstadoPedido = idEstadoPedido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


