package model.pojo;
// Generated 5/11/2015 05:15:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int idPedido;
     private Cliente cliente;
     private Estadopedido estadopedido;
     private Date fecha;
     private Set detallepedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int idPedido, Cliente cliente, Estadopedido estadopedido) {
        this.idPedido = idPedido;
        this.cliente = cliente;
        this.estadopedido = estadopedido;
    }
    public Pedido(int idPedido, Cliente cliente, Estadopedido estadopedido, Date fecha, Set detallepedidos) {
       this.idPedido = idPedido;
       this.cliente = cliente;
       this.estadopedido = estadopedido;
       this.fecha = fecha;
       this.detallepedidos = detallepedidos;
    }
   
    public int getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Estadopedido getEstadopedido() {
        return this.estadopedido;
    }
    
    public void setEstadopedido(Estadopedido estadopedido) {
        this.estadopedido = estadopedido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getDetallepedidos() {
        return this.detallepedidos;
    }
    
    public void setDetallepedidos(Set detallepedidos) {
        this.detallepedidos = detallepedidos;
    }




}


